In [1]:
import numpy as np
x = np.random.randint(low=0, high = 100, size=10)
y = np.random.randint(low=0, high = 100, size = 10)

In [2]:
#Finidng Unit vector. There is no built infunction in numpy to find unit vecotr.
# However we can get the unit vector by dividing it's lenght
unit_vector = x / np.linalg.norm(x)
unit_vector

array([0.19446919, 0.1129176 , 0.55831478, 0.15683   , 0.0125464 ,
       0.26347439, 0.33247959, 0.40775799, 0.33247959, 0.39521159])

In [3]:
# Calculating cosine similarity
# There is no builtin funciton in numpy for calculating that
cosine = np.dot(x, y) / np.linalg.norm(x) * np.linalg.norm(y)
cosine

24571.31187193605

In [4]:
# Calculating euclidean distance in numpy
euc_dis = np.sqrt(np.sum((x -y) ** 2))
euc_dis

121.58124855420756

In [5]:
b = x[:9]
b = b.reshape(3,3)
eigen_value, eigen_vector = np.linalg.eig(b)
print(f"Eigen value {eigen_value}")
print(f"Eigen vector {eigen_vector}")

Eigen value [134.9467498  -15.54357755 -33.40317225]
Eigen vector [[-0.64521861 -0.87049967 -0.78468124]
 [-0.33781341  0.29201512 -0.15724973]
 [-0.68525546  0.39617861  0.59962311]]
