In [1]:
# importing libraries
import numpy as np
from scipy import stats

In [2]:
# calculating mean median mode.
dataset = (np.random.rand(5,10) * 100).astype(int)
print(dataset)
# Axis 0 will take the mean along y axis, axis 1 will calculate mean along x axis
# keepdims will use the same dimension
print(f"Mean: {np.mean(dataset, axis=0, keepdims=True, dtype=int)}")
print(f"Median: {np.median(dataset, axis=0, keepdims=True)} ")
print(f"Mode: {stats.mode(dataset, axis=0)}")

[[44 23 47 25 41 35  7 23 24 13]
 [58 12 16 41 56 20 45 18 30  8]
 [38 26 94 19 68 41 21 67  0  9]
 [29 12 41 36 86 93 32 37 54 22]
 [97 42 49 20 34 44 54  1 36 57]]
Mean: [[53 23 49 28 57 46 31 29 28 21]]
Median: [[44. 23. 47. 25. 56. 41. 32. 23. 30. 13.]] 
Mode: ModeResult(mode=array([[29, 12, 16, 19, 34, 20,  7,  1,  0,  8]]), count=array([[1, 2, 1, 1, 1, 1, 1, 1, 1, 1]]))


C:\Users\4gTraders\AppData\Local\Temp\ipykernel_9928\2900587813.py:8: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  print(f"Mode: {stats.mode(dataset, axis=0)}")


<h3> 1.1.2 Normal Distribution </h3>

In [3]:
# Use numpy to find standard deviation
np.std(dataset, axis=0, keepdims=True)

array([[23.84449622, 11.06345335, 25.22379829,  8.79545337, 18.69759343,
        24.63006293, 16.72602762, 22.13052191, 17.55448661, 18.28004376]])

In [4]:
x = [-2.1, -1,  4.3]
y = [3,  1.1,  0.12]
z = np.stack((x, y), axis=0)
print(np.corrcoef(z))
print(np.corrcoef(x, y))
print(np.corrcoef(x))

[[ 1.         -0.85535781]
 [-0.85535781  1.        ]]
[[ 1.         -0.85535781]
 [-0.85535781  1.        ]]
1.0


In [5]:
# Find covariance using numpy
x = np.array([[2, 0], [1, 1], [0, 2]]).T
# x0 = 2, 1, 0
# x1 = 0, 1, 2
# If x0 increase x1 decrease so the covaraince is negetive
# Each row is treated as a single variable.
cov = np.cov(x)
print(x)
print(cov)

[[2 1 0]
 [0 1 2]]
[[ 1. -1.]
 [-1.  1.]]


In [6]:
x = [-2.1, -1,  4.3]
y = [3,  1.1,  0.12]
z = np.stack((x, y), axis=0)
print(np.cov(z))
print(np.cov(x, y))
print(np.cov(x))

[[11.71       -4.286     ]
 [-4.286       2.14413333]]
[[11.71       -4.286     ]
 [-4.286       2.14413333]]
11.709999999999999
